
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ViSED.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Accounts
{

    public int id { get; set; }

    public int role_id { get; set; }

    public int user_id { get; set; }

    public string login { get; set; }

    public string passw { get; set; }



    public virtual Roles Roles { get; set; }

    public virtual Users Users { get; set; }

}

}
