
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ViSED.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Admins
{

    public int id { get; set; }

    public int role_id { get; set; }

    public string login { get; set; }

    public string password { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public string thirdName { get; set; }



    public virtual Roles Roles { get; set; }

}

}
