
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ViSED.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DocType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DocType()
    {

        this.Letters = new HashSet<Letters>();

    }


    public int id { get; set; }

    public string Name { get; set; }

    public bool Use_Blank { get; set; }

    public bool Ierarhiya { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Letters> Letters { get; set; }

}

}
