//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViSED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public int from_user_id { get; set; }
        public int to_user_id { get; set; }
        public int doc_type_id { get; set; }
        public string text { get; set; }
        public string attachedFile { get; set; }
        public System.DateTime dateOfSend { get; set; }
        public Nullable<System.DateTime> dateOfRead { get; set; }
    
        public virtual DocType DocType { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
