
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ViSED.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TaskAttachments
{

    public int id { get; set; }

    public int id_task { get; set; }

    public string attachedFile { get; set; }

    public string attachedName { get; set; }



    public virtual Tasks Tasks { get; set; }

}

}
