
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ViSED.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tasks
{

    public int id { get; set; }

    public Nullable<int> id_letter { get; set; }

    public Nullable<int> user_id_from { get; set; }

    public int user_id_to { get; set; }

    public string taskText { get; set; }

    public bool complete { get; set; }

    public System.DateTime dateOfCreate { get; set; }

    public Nullable<System.DateTime> dateDeadline { get; set; }

    public int taskType { get; set; }

    public string taskName { get; set; }



    public virtual Letters Letters { get; set; }

    public virtual Users Users { get; set; }

    public virtual Users Users1 { get; set; }

}

}
