
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ViSED.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Users
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Users()
    {

        this.Accounts = new HashSet<Accounts>();

        this.MyDocs = new HashSet<MyDocs>();

        this.MyTask = new HashSet<MyTask>();

        this.MyTask1 = new HashSet<MyTask>();

    }


    public int id { get; set; }

    public int podrazdelenie_id { get; set; }

    public int dolgnst_id { get; set; }

    public string first_name { get; set; }

    public string second_name { get; set; }

    public string third_name { get; set; }

    public string indexNum { get; set; }

    public string foto { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Accounts> Accounts { get; set; }

    public virtual Dolgnosti Dolgnosti { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MyDocs> MyDocs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MyTask> MyTask { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MyTask> MyTask1 { get; set; }

    public virtual Podrazdeleniya Podrazdeleniya { get; set; }

}

}
